language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
#  - sudo add-apt-repository -y ppa:webupd8team/java
#  - sudo apt-get update
#  - sudo apt-get install -y oracle-java8-installer || true
#
#  - pushd /var/lib/dpkg/info
#  - sudo sed -i 's|JAVA_VERSION=8u161|JAVA_VERSION=8u172|' oracle-java8-installer.*
#  - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/|' oracle-java8-installer.*
#  - sudo sed -i 's|SHA256SUM_TGZ="6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"|SHA256SUM_TGZ="28a00b9400b6913563553e09e8024c286b506d8523334c93ddec6c9ec7e9d346"|' oracle-java8-installer.*
#  - sudo sed -i 's|J_DIR=jdk1.8.0_161|J_DIR=jdk1.8.0_172|' oracle-java8-installer.*
#  - popd
#  - sudo apt-get update
#
#  - sudo apt-get install -y oracle-java8-installer
  - chmod +x mvnw
branches:
  only:
  - master

before_script:


script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN


before_deploy:
  - mvn package && zip -r ./my_source_bundle.zip target/photoshare-0.0.1-SNAPSHOT.jar

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"
  app: "photoshare"
  env: "Photoshare-env"
  bucket_name: "elasticbeanstalk-us-east-1-925930642762"
  on:
    branch: deploy
  zip_file: "my_source_bundle.zip"
