language: java
sudo: true
dist: trusty
jdk: oraclejdk8
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
before_install:
#  - sudo add-apt-repository -y ppa:webupd8team/java
#  - sudo apt-get update
#  - sudo apt-get install -y oracle-java8-installer || true
#  # todo remove this kludge and the above || true when the ppa is fixed
#  - cd /var/lib/dpkg/info
#  - sudo sed -i 's|JAVA_VERSION=8u171|JAVA_VERSION=8u181|' oracle-java8-installer.*
#  - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/|' oracle-java8-installer.*
#  - sudo sed -i 's|SHA256SUM_TGZ="b6dd2837efaaec4109b36cfbb94a774db100029f98b0d78be68c27bec0275982"|SHA256SUM_TGZ="1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3"|' oracle-java8-installer.*
#  - sudo sed -i 's|J_DIR=jdk1.8.0_171|J_DIR=jdk1.8.0_181|' oracle-java8-installer.*
#  - sudo apt-get update
#  - sudo apt-get install -y oracle-java8-installer
#  - cd $TRAVIS_BUILD_DIR
  - chmod +x mvnw
branches:
  only:
  - master

script:
 - mvn test -B
 - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN


before_deploy:
  - mvn package && zip -r ./my_source_bundle.zip target/photoshare-0.0.1-SNAPSHOT.jar
  - python set_properties.py

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"
  app: "photoshare"
  env: "Photoshare-env"
  bucket_name: "elasticbeanstalk-us-east-1-925930642762"
  on:
    branch: deploy
  zip_file: "my_source_bundle.zip"
