branch-defaults:
  default:
    environment: Photoshare-env
environment-defaults:
  Photoshare-env:
    branch: null
    repository: null
global:
  application_name: photoshare
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Java 8 running on
    64bit Amazon Linux/2.8.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: my_source_bundle.zip
