package com.clou.photoshare.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.*;

import javax.validation.constraints.NotNull;


@DynamoDBTable(tableName = "Trip")
public class Trip {
    @NotNull
    private String id;

    @NotNull
    private String tripName;

    private Set<String> tripMember;

    public Trip() {  };

    public Trip(String id, String tripName, Set<String> tripMember) {
        this.id = id;
        this.tripName = tripName;
        this.tripMember = tripMember;
    }

    @DynamoDBHashKey(attributeName = "Id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "TripName")
    public String getTripName() {
        return tripName;
    }

    public void setTripName(String tripName) {
        this.tripName = tripName;
    }

    @DynamoDBAttribute(attributeName = "TripMember")
    public Set<String> getTripMember() {
        return tripMember;
    }

    public void setTripMember(Set<String> tripMember) {
        this.tripMember = tripMember;
    }

    public void addTripMember(String memberId) {
        this.tripMember.add(memberId);
    }

    public void addTripMember(Collection<String> memberId) {
        this.tripMember.addAll(memberId);
    }

    public void deleteTripMember (String memberId) {
        if (this.tripMember.contains(memberId)) {
            this.tripMember.remove(memberId);
        }
        else {
            throw new NoSuchElementException("Cannot find a member with ID: " + memberId);
        }
    }

    public void deleteTripMember(Collection<String> memberId) {
        this.tripMember.removeAll(memberId);
    }

    public boolean isTripMember(String memberId) {
        return this.tripMember.contains(memberId);
    }

    public ArrayList<Boolean> isTripMember(Collection<String> memberId) {
        ArrayList<Boolean> result = new ArrayList<>();
        for (String member : memberId) {
            result.add(this.tripName.contains(member));
        }
        return result;
    }

    @Override
    public String toString() {
        String joinedTripMemberId = String.join(",", this.tripMember);
        return String.format("Trip: id: %s, tripName: %s, tripMember: %s", id, tripName, joinedTripMemberId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;

        if(obj == null || obj.getClass()!= this.getClass())
            return false;

        Trip trip = (Trip) obj;
        return (
                trip.getId().equals(this.getId())
                        && trip.getTripName().equals(this.getTripName())
                        && trip.getTripMember().equals(this.getTripMember())
        );
    }
}
